[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["crates/*"]

[workspace.dependencies]
hdi = "=0.3.6"
hdk = "=0.2.6"
holo_hash = { version = "=0.2.6", features = ["encoding"] }
serde = "=1.0.166"
bincode = "1.3.3"
alloy-primitives = { version = "0.6.3", features = ["serde", "k256"] }
ed25519-dalek = { version = "2.1.1", features = ["serde"] }
bs58 = "0.5.0"
ethers-signers = "0.6.2"
holochain = { version = "0.2.6", default-features = false, features = [
  "test_utils",
] }
holochain_keystore = "0.2.6"

[workspace.dependencies.game_identity_types]
path = "crates/game_identity_types"

[workspace.dependencies.username_registry_validation]
path = "crates/username_registry_validation"

[workspace.dependencies.username_registry_integrity]
path = "crates/username_registry_integrity"

[workspace.dependencies.username_registry_coordinator]
path = "crates/username_registry_coordinator"

[workspace.dependencies.signer_coordinator]
path = "crates/signer_coordinator"
