[package]
name = "signer_zome"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "signer_zome"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
game_identity_types = { workspace = true }
