[package]
name = "username_registry"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "username_registry"

[dependencies]
hdk = { workspace = true }
username_registry_integrity = { workspace = true }
game_identity_types = { workspace = true }
