name: End-to-End Tests

on:
  push: {}

jobs:
  build-and-test:
    name: Build the happ & docker containers and run e2e tests
    runs-on: ubuntu-20.04
    steps:
      # Setup toolchain and caching
      - uses: actions/checkout@v3
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: 1.74
      - uses: docker/setup-buildx-action@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: cache node dependencies
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: node_modules-${{ hashFiles('**/package-lock.json')}}
      - run: npm i
      - uses: Swatinem/rust-cache@v2

      # Build all
      - run: docker/build_containers.sh

      # Test
      - run: |
          npm run dev -w @game-identity/e2e &
          npm run test -w @game-identity/e2e
